/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -p accounts_interface /root/Downloads/cutefish/libcutefish/accounts/org.freedesktop.Accounts.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "accounts_interface.h"

/*
 * Implementation of interface class OrgFreedesktopAccountsInterface
 */

OrgFreedesktopAccountsInterface::OrgFreedesktopAccountsInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopAccountsInterface::~OrgFreedesktopAccountsInterface()
{
}


#include "accounts_interface.moc"
