/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -p user_interface /root/Downloads/cutefish/libcutefish/accounts/org.freedesktop.Accounts.User.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "user_interface.h"

/*
 * Implementation of interface class OrgFreedesktopAccountsUserInterface
 */

OrgFreedesktopAccountsUserInterface::OrgFreedesktopAccountsUserInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopAccountsUserInterface::~OrgFreedesktopAccountsUserInterface()
{
}


#include "user_interface.moc"
