// This file is autogenerated. Changes will be overwritten.
#include "P66WHCG54J/moc_control.cpp"
#include "P66WHCG54J/moc_orientation_sensor.cpp"
#include "EWIEGA46WW/moc_confighandler.cpp"
#include "EWIEGA46WW/moc_outputmodel.cpp"
#include "EWIEGA46WW/moc_screen.cpp"
